kind: Service
apiVersion: v1
metadata:
  name: kubernetes-event-logger
  namespace: kube-system
  labels:
    application: kubernetes-event-logger
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    application: kubernetes-event-logger
